### ISSUE TITLE
Can't flatten array of int to array of v

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/pylabrad#96]

**Comment by afowler** [comment]
Pushed fix for fasttypes, issue still present in types:

C:\Python-2.7.9\project_1_fasttypes\Release>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
'>>> import labrad.types as t
'>>> import numpy as np
'>>> t.flatten([-1,2,3],'*v')
('\x00\x00\x00\x03\xbf\xf0\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00', LRList(LRValue(''), depth=1))
'>>> a=np.array([-1,2,3],dtype=int)
'>>> t.flatten(a,'*v')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\git\pylabrad\labrad\types.py", line 326, in flatten
    s, t = _flatten_to(obj, types, endianness)
  File "c:\git\pylabrad\labrad\types.py", line 382, in _flatten_to
    raise FlatteningError(obj, types)
labrad.types.FlatteningError: (12345) Could not flatten array([-1,  2,  3]) to ['*v']. [payload=None]
'>>> import fasttypes as ft
'>>> ft.flatten([-1,2,3],'*v')
('\x00\x00\x00\x03\xbf\xf0\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00', '*v[]')
'>>> ft.flatten(a,'*v')
('\x00\x00\x00\x03\xbf\xf0\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x00@\x08\x00\x00\x00\x00\x00\x00', '*v[]')
'>>>

**Comment by DanielSank** [comment]
To make something show up as code, fence it with triple backticks. I'll do it here:

```
here is some fixed with text
and some code

void my_func(int x){
...
}
```
Hit the edit button to see the source of this comment.
